assets_version: 7
default_artwork: ninjagrl-seattle
artists:
    ninjagrl:
        name: ninjagrl
        url: http://ninjagrl.com
    tonytaj:
        name: Tony Taj
        url: http://tonytaj.com
    johnosgood:
        name: John Osgood
        url: http://johnosgood.com
artworks:
    johnosgood-sitka-pt3:
        by: johnosgood
        title: '"Sitka part 3"'
        symlink: johnosgood-sitka-pt3

    ninjagrl-seattle:
        by: ninjagrl
        title: '"puget sound" photograph'
        symlink: ninjagrl-seattle
    ninjagrl-music:
        by: ninjagrl
        title: '"sets in its place each dainty dish"'
        symlink: ninjagrl-music
    tonytaj-summer-in-the-city:
        by: tonytaj
        title: '"Summer Fun in the City"'
        symlink: tonytaj-summer-fun-in-the-city
        url: http://tonytaj.com/30jizvwhioft19x693hsbq3oc3fppd
